### PR TITLE
Change date format and refactor

### PR DESCRIPTION
**Pull request by horihiro**
Change date format to japanese style and reduce nest level.

### CODE REVIEW

**Comment by koudaiii** [comment]
Thank you for pull request! LGTM! But, this pull request is conflict. I will try resolve. If you like, cloud you resolve the conflict?  👀

**Comment by horihiro** [comment]
resolve conflict and change text style dynamically w/o reloading

**Comment by horihiro** [comment]
And fix version number

**Comment by koudaiii** [comment]
LGTM 😄  Thank you for pull request 👍

**Pull request merged**
